import { Contribution } from "./contribution-rules";

export const sharedMockDataset: Contribution[] = [
  {
    id: "VOC-KNG-001",
    contributor_id: "usr_expert_77",
    contributor_name: "Jasper Dahl",
    dialect: "Kangri",
    word_devanagari: "पहाड़",
    meaning:
      "पर्वत, ऊँचा भूभाग। विशाल प्राकृतिक संरचना जो आस-पास की भूमि से काफी ऊँची होती है।",
    example_sentence: "तुसां पहाड़ कजो जांदे दे?",
    region: "Palampur",
    category: "Nature & Geography",
    word_latin: "pahad",
    ipa: "pəɦaːɽ",
    meaning_hindi: "पर्वत",
    meaning_english: "Mountain",
    example_sentence_english: "Why are you going to the mountains?",
    example_sentence_hindi: "आप पहाड़ क्यों जा रहे हैं?",
    status: "under_review",
    review_comments: [
      {
        id: "RC-KNG-001",
        author_id: "usr_head_11",
        author_name: "Meera Thakur",
        field_name: "Latin Text",
        message:
          "Please add the diacritic form so the retroflex sound is clear.",
        status: "open",
        created_at: "2026-07-03T09:20:00.000Z",
        resolved_at: null,
        resolved_by: null,
      },
      {
        id: "RC-KNG-002",
        author_id: "usr_expert_21",
        author_name: "Dev Sharma",
        field_name: "Meaning",
        message:
          "The second sentence is helpful. Keep the first phrase concise.",
        status: "resolved",
        created_at: "2026-07-03T09:42:00.000Z",
        resolved_at: "2026-07-03T10:16:00.000Z",
        resolved_by: "usr_expert_77",
      },
    ],
    history: [
      {
        id: "HE-KNG-001",
        type: "submitted",
        actor_id: "usr_expert_77",
        actor_name: "Jasper Dahl",
        message: "Submitted for review.",
        created_at: "2026-07-03T08:50:00.000Z",
      },
      {
        id: "HE-KNG-002",
        type: "comment_added",
        actor_id: "usr_head_11",
        actor_name: "Meera Thakur",
        message: "Requested a clearer Latin transliteration.",
        created_at: "2026-07-03T09:20:00.000Z",
      },
    ],
    flag_reason: null,
    flagged_by: null,
    rejected_reason: null,
    rejected_by: null,
    approved_by: null,
    approved_at: null,
    created_at: "2026-07-03T08:45:00.000Z",
    updated_at: "2026-07-03T10:16:00.000Z",
  },
  {
    id: "VOC-MND-002",
    contributor_id: "usr_contrib_13",
    contributor_name: "Ananya Rana",
    dialect: "Mandyali",
    word_devanagari: "ओतड़",
    meaning:
      "ऐसी भूमि जहाँ सिंचाई की सुविधा न हो, पूरी तरह वर्षा पर निर्भर सूखी जमीन।",
    example_sentence: "एतकी ओतड़ा री जमीना च कनक नी होई।",
    region: "Sundernagar",
    category: "Agriculture & Land",
    word_latin: "otar",
    ipa: "oːt̪əɽ",
    meaning_hindi: "असिंचित भूमि",
    meaning_english: "Unirrigated dry land",
    example_sentence_english:
      "This year wheat did not grow well on the unirrigated land.",
    example_sentence_hindi: "इस साल असिंचित भूमि में गेहूं नहीं हुआ।",
    status: "under_review",
    review_comments: [
      {
        id: "RC-MND-001",
        author_id: "usr_expert_77",
        author_name: "Jasper Dahl",
        field_name: "Example Sentence",
        message:
          "This sentence is strong, but the Hindi translation should mirror the crop failure more directly.",
        status: "open",
        created_at: "2026-07-04T11:20:00.000Z",
        resolved_at: null,
        resolved_by: null,
      },
    ],
    history: [
      {
        id: "HE-MND-001",
        type: "submitted",
        actor_id: "usr_contrib_13",
        actor_name: "Ananya Rana",
        message: "Submitted for review.",
        created_at: "2026-07-04T10:30:00.000Z",
      },
      {
        id: "HE-MND-002",
        type: "comment_added",
        actor_id: "usr_expert_77",
        actor_name: "Jasper Dahl",
        message: "Requested a tighter example translation.",
        created_at: "2026-07-04T11:20:00.000Z",
      },
    ],
    flag_reason: null,
    flagged_by: null,
    rejected_reason: null,
    rejected_by: null,
    approved_by: null,
    approved_at: null,
    created_at: "2026-07-04T10:25:00.000Z",
    updated_at: "2026-07-04T11:20:00.000Z",
  },
  {
    id: "VOC-KUL-003",
    contributor_id: "usr_contrib_14",
    contributor_name: "Rohit Negi",
    dialect: "Kulluvi",
    word_devanagari: "काउणी",
    meaning:
      "एक प्रकार का पहाड़ी बारीक अनाज, जिसे फॉक्सटेल मिलेट भी कहा जाता है।",
    example_sentence: "काउणी री खीर बड़ी सवादू हुंदी।",
    region: "Naggar",
    category: "Food & Culinary",
    word_latin: "kauni",
    ipa: "kaːuɳiː",
    meaning_hindi: "कंगनी",
    meaning_english: "Foxtail millet",
    example_sentence_english:
      "The pudding made with foxtail millet is very delicious.",
    example_sentence_hindi: "कंगनी की खीर बहुत स्वादिष्ट होती है।",
    status: "approved",
    review_comments: [
      {
        id: "RC-KUL-001",
        author_id: "usr_expert_21",
        author_name: "Dev Sharma",
        field_name: "Meaning",
        message: "Add the common English crop name.",
        status: "resolved",
        created_at: "2026-07-01T14:05:00.000Z",
        resolved_at: "2026-07-01T15:14:00.000Z",
        resolved_by: "usr_contrib_14",
      },
    ],
    history: [
      {
        id: "HE-KUL-001",
        type: "submitted",
        actor_id: "usr_contrib_14",
        actor_name: "Rohit Negi",
        message: "Submitted for review.",
        created_at: "2026-07-01T13:30:00.000Z",
      },
      {
        id: "HE-KUL-002",
        type: "comment_resolved",
        actor_id: "usr_contrib_14",
        actor_name: "Rohit Negi",
        message: "Resolved crop name clarification.",
        created_at: "2026-07-01T15:14:00.000Z",
      },
      {
        id: "HE-KUL-003",
        type: "approved",
        actor_id: "usr_head_11",
        actor_name: "Meera Thakur",
        message: "Approved after all review comments were resolved.",
        created_at: "2026-07-01T15:40:00.000Z",
      },
    ],
    flag_reason: null,
    flagged_by: null,
    rejected_reason: null,
    rejected_by: null,
    approved_by: "Meera Thakur",
    approved_at: "2026-07-01T15:40:00.000Z",
    created_at: "2026-07-01T13:25:00.000Z",
    updated_at: "2026-07-01T15:40:00.000Z",
  },
  {
    id: "VOC-SIR-004",
    contributor_id: "usr_contrib_18",
    contributor_name: "Kabir Chauhan",
    dialect: "Sirmauri",
    word_devanagari: "झाकड़ी",
    meaning:
      "मिट्टी का छोटा बर्तन जिसका उपयोग छाछ या दही रखने के लिए किया जाता है।",
    example_sentence: "झाकड़िया दी छाछ ठंडी रहंदी।",
    region: "Nahan",
    category: "Household Objects",
    word_latin: "jhakhri",
    ipa: "ɟʱaːkəɽiː",
    meaning_hindi: "छोटी मटकी",
    meaning_english: "Small earthen pot",
    example_sentence_english:
      "Buttermilk remains cool in the small earthen pot.",
    example_sentence_hindi: "छोटी मटकी में छाछ ठंडी रहती है।",
    status: "flagged",
    review_comments: [
      {
        id: "RC-SIR-001",
        author_id: "usr_expert_77",
        author_name: "Jasper Dahl",
        field_name: "IPA",
        message: "The recorded pronunciation and IPA do not appear to match.",
        status: "open",
        created_at: "2026-07-05T09:12:00.000Z",
        resolved_at: null,
        resolved_by: null,
      },
    ],
    history: [
      {
        id: "HE-SIR-001",
        type: "submitted",
        actor_id: "usr_contrib_18",
        actor_name: "Kabir Chauhan",
        message: "Submitted for review.",
        created_at: "2026-07-05T08:50:00.000Z",
      },
      {
        id: "HE-SIR-002",
        type: "flagged",
        actor_id: "usr_expert_77",
        actor_name: "Jasper Dahl",
        message:
          "Flagged because IPA and oral pronunciation need authority review.",
        created_at: "2026-07-05T09:20:00.000Z",
      },
    ],
    flag_reason:
      "IPA and recorded pronunciation appear inconsistent for the Sirmauri form.",
    flagged_by: "Jasper Dahl",
    rejected_reason: null,
    rejected_by: null,
    approved_by: null,
    approved_at: null,
    created_at: "2026-07-05T08:45:00.000Z",
    updated_at: "2026-07-05T09:20:00.000Z",
  },
  {
    id: "VOC-CHM-005",
    contributor_id: "usr_contrib_15",
    contributor_name: "Tsering Verma",
    dialect: "Chameali",
    word_devanagari: "हंज",
    meaning:
      "आंक से निकलने वाले आंसू; दुख या अत्यधिक हर्ष के समय निकलने वाला जल।",
    example_sentence: "तेरी अक्खी च हंज कजो आए?",
    region: "Bharmour",
    category: "Human Emotions",
    word_latin: "hanj",
    ipa: "ɦəɲɟ",
    meaning_hindi: "आंसू",
    meaning_english: "Tears",
    example_sentence_english: "Why did tears come into your eyes?",
    example_sentence_hindi: "तुम्हारी आंख में आंसू क्यों आए?",
    status: "rejected",
    review_comments: [
      {
        id: "RC-CHM-001",
        author_id: "usr_head_11",
        author_name: "Meera Thakur",
        field_name: "Dialect",
        message: "This appears to be entered under the wrong dialect.",
        status: "rejected",
        created_at: "2026-07-02T12:00:00.000Z",
        resolved_at: "2026-07-02T12:45:00.000Z",
        resolved_by: "usr_contrib_15",
      },
    ],
    history: [
      {
        id: "HE-CHM-001",
        type: "submitted",
        actor_id: "usr_contrib_15",
        actor_name: "Tsering Verma",
        message: "Submitted for review.",
        created_at: "2026-07-02T11:30:00.000Z",
      },
      {
        id: "HE-CHM-002",
        type: "rejected",
        actor_id: "usr_head_11",
        actor_name: "Meera Thakur",
        message:
          "Rejected because the dialect attribution needs a new submission.",
        created_at: "2026-07-02T13:00:00.000Z",
      },
    ],
    flag_reason: null,
    flagged_by: null,
    rejected_reason: "Dialect attribution conflicts with the source note.",
    rejected_by: "Meera Thakur",
    approved_by: null,
    approved_at: null,
    created_at: "2026-07-02T11:25:00.000Z",
    updated_at: "2026-07-02T13:00:00.000Z",
  },
  {
    id: "VOC-KIN-006",
    contributor_id: "usr_expert_77",
    contributor_name: "Jasper Dahl",
    dialect: "Kinnauri",
    word_devanagari: "रिंगपा",
    meaning: "बुद्धिमान, चतुर या गहरी समझ रखने वाला व्यक्ति।",
    example_sentence: "एश मती रिंगपा मीश बा।",
    region: "Kalpa",
    category: "Human Characteristics",
    word_latin: "ringpa",
    ipa: "ɾiŋpaː",
    meaning_hindi: "बुद्धिमान",
    meaning_english: "Wise person",
    example_sentence_english: "This boy is very wise.",
    example_sentence_hindi: "यह लड़का बहुत बुद्धिमान है।",
    status: "under_review",
    review_comments: [],
    history: [
      {
        id: "HE-KIN-001",
        type: "edited",
        actor_id: "usr_expert_77",
        actor_name: "Jasper Dahl",
        message: "Saved draft vocabulary entry.",
        created_at: "2026-07-06T07:40:00.000Z",
      },
    ],
    flag_reason: null,
    flagged_by: null,
    rejected_reason: null,
    rejected_by: null,
    approved_by: null,
    approved_at: null,
    created_at: "2026-07-06T07:35:00.000Z",
    updated_at: "2026-07-06T07:40:00.000Z",
  },
  {
    id: "VOC-KNG-007",
    contributor_id: "usr_expert_77",
    contributor_name: "Jasper Dahl",
    dialect: "Kangri",
    word_devanagari: "द्रमड़",
    meaning: "जुताई के बाद खेत में बचा मिट्टी का कड़ा ढेला।",
    example_sentence: "खेत च द्रमड़ भंने पउणे।",
    region: "Dharamshala",
    category: "Agriculture & Land",
    word_latin: "dramar",
    ipa: "d̪ɾəməɽ",
    meaning_hindi: "मिट्टी का ढेला",
    meaning_english: "Clod of earth",
    example_sentence_english: "We need to break the clods in the field.",
    example_sentence_hindi: "खेत में मिट्टी के ढेले तोड़ने पड़ेंगे।",
    status: "flagged",
    review_comments: [
      {
        id: "RC-KNG-007",
        author_id: "usr_head_11",
        author_name: "Meera Thakur",
        field_name: "Latin Text",
        message: "Use a retroflex marker in the transliteration.",
        status: "open",
        created_at: "2026-07-06T13:10:00.000Z",
        resolved_at: null,
        resolved_by: null,
      },
    ],
    history: [
      {
        id: "HE-KNG-007A",
        type: "submitted",
        actor_id: "usr_expert_77",
        actor_name: "Jasper Dahl",
        message: "Submitted for review.",
        created_at: "2026-07-06T12:45:00.000Z",
      },
      {
        id: "HE-KNG-007B",
        type: "flagged",
        actor_id: "usr_head_11",
        actor_name: "Meera Thakur",
        message: "Flagged until transliteration is corrected.",
        created_at: "2026-07-06T13:12:00.000Z",
      },
    ],
    flag_reason: "Transliteration needs retroflex notation before publication.",
    flagged_by: "Meera Thakur",
    rejected_reason: null,
    rejected_by: null,
    approved_by: null,
    approved_at: null,
    created_at: "2026-07-06T12:40:00.000Z",
    updated_at: "2026-07-06T13:12:00.000Z",
  },
  {
    id: "VOC-MND-008",
    contributor_id: "usr_contrib_13",
    contributor_name: "Ananya Rana",
    dialect: "Mandyali",
    word_devanagari: "गाम",
    meaning: "धूप; सूरज की गर्मी जो ठंडे दिनों में सुखद लगती है।",
    example_sentence: "चला बहरी गामा च बअते।",
    region: "Joginder Nagar",
    category: "Nature & Geography",
    word_latin: "gam",
    ipa: "ɡaːm",
    meaning_hindi: "धूप",
    meaning_english: "Sunshine",
    example_sentence_english: "Come, let us sit outside in the sunshine.",
    example_sentence_hindi: "चलो बाहर धूप में बैठते हैं।",
    status: "approved",
    review_comments: [],
    history: [
      {
        id: "HE-MND-008A",
        type: "submitted",
        actor_id: "usr_contrib_13",
        actor_name: "Ananya Rana",
        message: "Submitted for review.",
        created_at: "2026-07-03T12:00:00.000Z",
      },
      {
        id: "HE-MND-008B",
        type: "approved",
        actor_id: "usr_expert_77",
        actor_name: "Jasper Dahl",
        message: "Approved with no unresolved review comments.",
        created_at: "2026-07-03T12:35:00.000Z",
      },
    ],
    flag_reason: null,
    flagged_by: null,
    rejected_reason: null,
    rejected_by: null,
    approved_by: "Jasper Dahl",
    approved_at: "2026-07-03T12:35:00.000Z",
    created_at: "2026-07-03T11:50:00.000Z",
    updated_at: "2026-07-03T12:35:00.000Z",
  },

  // --- NEW ADDITIONS TO THOROUGHLY TEST WORKFLOW ENGINE ---

  {
    id: "VOC-MND-009",
    contributor_id: "usr_contrib_13",
    contributor_name: "Ananya Rana",
    dialect: "Mandyali",
    word_devanagari: "ब्यागा",
    meaning: "सुबह का समय, भोर। तड़के का वक्त जब सूरज उगता है।",
    example_sentence: "हूँ ब्यागा दिल्ली जो जाणा।",
    region: "Mandi",
    category: "Time & Seasons",
    word_latin: "byaga",
    ipa: "bjaːɡaː",
    meaning_hindi: "सुबह",
    meaning_english: "Morning",
    example_sentence_english: "I have to leave for Delhi early in the morning.",
    example_sentence_hindi: "मुझे सुबह जल्दी दिल्ली के लिए निकलना है।",
    status: "under_review",
    review_comments: [], // Pristine condition: under_review with 0 comments. Expert can approve directly!
    history: [
      {
        id: "HE-MND-009A",
        type: "submitted",
        actor_id: "usr_contrib_13",
        actor_name: "Ananya Rana",
        message: "Submitted freshly harvested dialect entry.",
        created_at: "2026-07-07T06:00:00.000Z",
      },
    ],
    flag_reason: null,
    flagged_by: null,
    rejected_reason: null,
    rejected_by: null,
    approved_by: null,
    approved_at: null,
    created_at: "2026-07-07T05:50:00.000Z",
    updated_at: "2026-07-07T06:00:00.000Z",
  },
  {
    id: "VOC-KUL-010",
    contributor_id: "usr_contrib_14",
    contributor_name: "Rohit Negi",
    dialect: "Kulluvi",
    word_devanagari: "थुआ",
    meaning: "गाय या भैंस का निकाला हुआ ताजा मक्खन जो गर्म न किया गया हो।",
    example_sentence: "रोटी च थुआ लगाइके खा।",
    region: "Manali",
    category: "Food & Culinary",
    word_latin: "thua",
    ipa: "t̪ʰuaː",
    meaning_hindi: "ताजा मक्खन",
    meaning_english: "Fresh unsalted butter",
    example_sentence_english:
      "Eat the bread after spreading fresh butter on it.",
    example_sentence_hindi: "रोटी पर ताजा मक्खन लगाकर खाओ।",
    status: "under_review",
    review_comments: [
      {
        id: "RC-KUL-010A",
        author_id: "usr_expert_21",
        author_name: "Dev Sharma",
        field_name: "IPA",
        message: "Ensure dental tʰ marker is accurate.",
        status: "open", // Open comment! Regular expert CANNOT approve this. Only Language Head / Admin can bypass.
        created_at: "2026-07-07T08:30:00.000Z",
        resolved_at: null,
        resolved_by: null,
      },
    ],
    history: [
      {
        id: "HE-KUL-010A",
        type: "submitted",
        actor_id: "usr_contrib_14",
        actor_name: "Rohit Negi",
        message: "Submitted item.",
        created_at: "2026-07-07T08:00:00.000Z",
      },
      {
        id: "HE-KUL-010B",
        type: "comment_added",
        actor_id: "usr_expert_21",
        actor_name: "Dev Sharma",
        message: "Added question on dental retroflex clarity.",
        created_at: "2026-07-07T08:30:00.000Z",
      },
    ],
    flag_reason: null,
    flagged_by: null,
    rejected_reason: null,
    rejected_by: null,
    approved_by: null,
    approved_at: null,
    created_at: "2026-07-07T07:55:00.000Z",
    updated_at: "2026-07-07T08:30:00.000Z",
  },
  {
    id: "VOC-CHM-011",
    contributor_id: "usr_expert_21", // Contributed by an expert role actor
    contributor_name: "Dev Sharma",
    dialect: "Chameali",
    word_devanagari: "दारकर",
    meaning: "लकड़ी चीरने या काटने वाला बढ़ई या कामगार।",
    example_sentence: "दारकर जो कोठड़े री मरम्मत तांई सदो।",
    region: "Chamba",
    category: "Occupations",
    word_latin: "darkar",
    ipa: "d̪aːɾkəɾ",
    meaning_hindi: "बढ़ई",
    meaning_english: "Carpenter",
    example_sentence_english:
      "Call the carpenter to repair the wooden granary store.",
    example_sentence_hindi: "कोठड़े की मरम्मत के लिए बढ़ई को बुलाओ।",
    status: "under_review",
    review_comments: [], // Test case: Even though contributor is an Expert, canReview prevents self-reviewing or self-approving.
    history: [
      {
        id: "HE-CHM-011A",
        type: "submitted",
        actor_id: "usr_expert_21",
        actor_name: "Dev Sharma",
        message: "Expert submitted fieldwork data.",
        created_at: "2026-07-06T15:00:00.000Z",
      },
    ],
    flag_reason: null,
    flagged_by: null,
    rejected_reason: null,
    rejected_by: null,
    approved_by: null,
    approved_at: null,
    created_at: "2026-07-06T14:45:00.000Z",
    updated_at: "2026-07-06T15:00:00.000Z",
  },
  {
    id: "VOC-SIR-012",
    contributor_id: "usr_contrib_18",
    contributor_name: "Kabir Chauhan",
    dialect: "Sirmauri",
    word_devanagari: "घियाली",
    meaning: "घी और चीनी के साथ बनाया गया गाढ़ा पारंपरिक दलिया या हलवा।",
    example_sentence: "त्याउरा दे दिहाड़े घियाली बणाई थी।",
    region: "Rajgarh",
    category: "Food & Culinary",
    word_latin: "ghiyali",
    ipa: "ɡʱijaːliː",
    meaning_hindi: "पारंपरिक हलवा",
    meaning_english: "Traditional sweet clarified butter pudding",
    example_sentence_english: "Ghiyali was prepared on the festival day.",
    example_sentence_hindi: "त्योहार के दिन घियाली बनाई गई थी।",
    status: "approved",
    review_comments: [
      {
        id: "RC-SIR-012A",
        author_id: "usr_head_11",
        author_name: "Meera Thakur",
        field_name: "Meaning English",
        message: "Make the definition descriptive of the specific fats used.",
        status: "resolved",
        created_at: "2026-07-02T10:00:00.000Z",
        resolved_at: "2026-07-02T11:15:00.000Z",
        resolved_by: "usr_contrib_18",
      },
    ],
    history: [
      {
        id: "HE-SIR-012A",
        type: "submitted",
        actor_id: "usr_contrib_18",
        actor_name: "Kabir Chauhan",
        message: "Submitted recipe record.",
        created_at: "2026-07-02T09:15:00.000Z",
      },
      {
        id: "HE-SIR-012B",
        type: "comment_resolved",
        actor_id: "usr_contrib_18",
        actor_name: "Kabir Chauhan",
        message: "Addressed descriptor requirements.",
        created_at: "2026-07-02T11:15:00.000Z",
      },
      {
        id: "HE-SIR-012C",
        type: "approved",
        actor_id: "usr_head_11",
        actor_name: "Meera Thakur",
        message: "Approved to production registry.",
        created_at: "2026-07-02T12:00:00.000Z",
      },
    ],
    flag_reason: null,
    flagged_by: null,
    rejected_reason: null,
    rejected_by: null,
    approved_by: "Meera Thakur",
    approved_at: "2026-07-02T12:00:00.000Z",
    created_at: "2026-07-02T09:00:00.000Z",
    updated_at: "2026-07-02T12:00:00.000Z",
  },
  {
    id: "VOC-KNG-013",
    contributor_id: "usr_contrib_22",
    contributor_name: "Priya Katoch",
    dialect: "Kangri",
    word_devanagari: "खुड्ड",
    meaning: "दीवार या चट्टान में बना छोटा सा गड्ढा अथवा ताक (आला)।",
    example_sentence: "दीवे जो खुड्डा च रखी दे।",
    region: "Kangra",
    category: "Household Objects",
    word_latin: "khudd",
    ipa: "kʰʊɖɖ",
    meaning_hindi: "आला या ताक",
    meaning_english: "Niche or small alcove in a wall",
    example_sentence_english: "Place the oil lamp inside the wall niche.",
    example_sentence_hindi: "दिए को ताक में रख दो।",
    status: "flagged",
    review_comments: [
      {
        id: "RC-KNG-013A",
        author_id: "usr_expert_21",
        author_name: "Dev Sharma",
        field_name: "Meaning Hindi",
        message: "Check if alcove fits domestic usage better than hole.",
        status: "open",
        created_at: "2026-07-06T10:20:00.000Z",
        resolved_at: null,
        resolved_by: null,
      },
    ],
    history: [
      {
        id: "HE-KNG-013A",
        type: "submitted",
        actor_id: "usr_contrib_22",
        actor_name: "Priya Katoch",
        message: "Initial insert.",
        created_at: "2026-07-06T09:00:00.000Z",
      },
      {
        id: "HE-KNG-013B",
        type: "flagged",
        actor_id: "usr_expert_21",
        actor_name: "Dev Sharma",
        message: "Flagging for architectural categorization checking.",
        created_at: "2026-07-06T10:25:00.000Z",
      },
    ],
    flag_reason:
      "Requires clarification by Language Head regarding structural terms.",
    flagged_by: "Dev Sharma",
    rejected_reason: null,
    rejected_by: null,
    approved_by: null,
    approved_at: null,
    created_at: "2026-07-06T08:45:00.000Z",
    updated_at: "2026-07-06T10:25:00.000Z",
  },
  {
    id: "VOC-MND-014",
    contributor_id: "usr_contrib_13",
    contributor_name: "Ananya Rana",
    dialect: "Mandyali",
    word_devanagari: "तिखरु",
    meaning: "तेज धूप या भयंकर गर्मी जो शरीर झुलसा दे।",
    example_sentence: "बाहरी मती तिखरु है, अजे मत जा।",
    region: "Sarkaghat",
    category: "Nature & Geography",
    word_latin: "tikharu",
    ipa: "t̪ɪkʰəɾu",
    meaning_hindi: "कड़ी धूप",
    meaning_english: "Scorching radiant heat or intense sunshine",
    example_sentence_english: "It is very scorching outside, do not go yet.",
    example_sentence_hindi: "बाहर बहुत तेज धूप है, अभी मत जाओ।",
    status: "rejected",
    review_comments: [], // Rejected items are immutable terminal states according to WORKFLOW_RULES
    history: [
      {
        id: "HE-MND-014A",
        type: "submitted",
        actor_id: "usr_contrib_13",
        actor_name: "Ananya Rana",
        message: "Submitting climate definition.",
        created_at: "2026-07-01T11:00:00.000Z",
      },
      {
        id: "HE-MND-014B",
        type: "rejected",
        actor_id: "usr_head_11",
        actor_name: "Meera Thakur",
        message: "Duplicate profile entry detected.",
        created_at: "2026-07-02T14:00:00.000Z",
      },
    ],
    flag_reason: null,
    flagged_by: null,
    rejected_reason: "Exact duplicate variant already recorded in database.",
    rejected_by: "Meera Thakur",
    approved_by: null,
    approved_at: null,
    created_at: "2026-07-01T10:40:00.000Z",
    updated_at: "2026-07-02T14:00:00.000Z",
  },
  {
    id: "VOC-KIN-015",
    contributor_id: "usr_contrib_33",
    contributor_name: "Sonam Gyaltson",
    dialect: "Kinnauri",
    word_devanagari: "ज़ोम",
    meaning: "याक और गाय के मेल से पैदा होने वाला एक संकर मवेशी पशु।",
    example_sentence: "ज़ोमा दा दूध गाढ़ा हुंद बा।",
    region: "Pooh",
    category: "Animals & Wildlife",
    word_latin: "zom",
    ipa: "zom",
    meaning_hindi: "चौरी गाय (याक संकर)",
    meaning_english: "Hybrid cattle female (cross of yak and cow)",
    example_sentence_english: "The milk of the hybrid cattle is thick.",
    example_sentence_hindi: "चौरी गाय का दूध गाढ़ा होता है।",
    status: "under_review",
    review_comments: [
      {
        id: "RC-KIN-015A",
        author_id: "usr_expert_77",
        author_name: "Jasper Dahl",
        field_name: "IPA",
        message:
          "Is the phonetic onset a real sibilant 'z' or an unaspirated affricate?",
        status: "open",
        created_at: "2026-07-07T14:20:00.000Z",
        resolved_at: null,
        resolved_by: null,
      },
      {
        id: "RC-KIN-015B",
        author_id: "usr_head_11",
        author_name: "Meera Thakur",
        field_name: "Meaning Hindi",
        message: "Local identification tags look correct.",
        status: "resolved",
        created_at: "2026-07-07T15:10:00.000Z",
        resolved_at: "2026-07-07T16:00:00.000Z",
        resolved_by: "usr_head_11",
      },
    ],
    history: [
      {
        id: "HE-KIN-015A",
        type: "submitted",
        actor_id: "usr_contrib_33",
        actor_name: "Sonam Gyaltson",
        message: "Submitted crossbreed classification entry.",
        created_at: "2026-07-07T13:00:00.000Z",
      },
      {
        id: "HE-KIN-015B",
        type: "comment_added",
        actor_id: "usr_expert_77",
        actor_name: "Jasper Dahl",
        message: "Added question on phonology context.",
        created_at: "2026-07-07T14:20:00.000Z",
      },
    ],
    flag_reason: null,
    flagged_by: null,
    rejected_reason: null,
    rejected_by: null,
    approved_by: null,
    approved_at: null,
    created_at: "2026-07-07T12:12:00.000Z",
    updated_at: "2026-07-07T16:00:00.000Z",
  },
  {
    id: "VOC-KUL-016",
    contributor_id: "usr_contrib_14",
    contributor_name: "Rohit Negi",
    dialect: "Kulluvi",
    word_devanagari: "खश",
    meaning: "खड़े ढालदार पहाड़ों पर बिछी सूखी फिसलन भरी घास।",
    example_sentence: "खशा पई पैर पिछला हुंदा।",
    region: "Sainj",
    category: "Nature & Geography",
    word_latin: "khash",
    ipa: "kʰəʃ",
    meaning_hindi: "फिसलन वाली सूखी घास",
    meaning_english: "Dry slippery mountain grass variety",
    example_sentence_english: "Feet tend to slip on the dry mountain grass.",
    example_sentence_hindi: "सूखी घास पर पैर फिसलता है।",
    status: "under_review",
    review_comments: [
      {
        id: "RC-KUL-016A",
        author_id: "usr_expert_21",
        author_name: "Dev Sharma",
        field_name: "Example Sentence English",
        message: "Translation flows very well.",
        status: "resolved", // Resolved comment! Entry can be approved by standard expert now!
        created_at: "2026-07-05T09:00:00.000Z",
        resolved_at: "2026-07-05T10:00:00.000Z",
        resolved_by: "usr_expert_21",
      },
    ],
    history: [
      {
        id: "HE-KUL-016A",
        type: "submitted",
        actor_id: "usr_contrib_14",
        actor_name: "Rohit Negi",
        message: "Submitted.",
        created_at: "2026-07-05T08:12:00.000Z",
      },
      {
        id: "HE-KUL-016B",
        type: "comment_resolved",
        actor_id: "usr_expert_21",
        actor_name: "Dev Sharma",
        message: "Closed context exploration favorably.",
        created_at: "2026-07-05T10:00:00.000Z",
      },
    ],
    flag_reason: null,
    flagged_by: null,
    rejected_reason: null,
    rejected_by: null,
    approved_by: null,
    approved_at: null,
    created_at: "2026-07-05T08:00:00.000Z",
    updated_at: "2026-07-05T10:00:00.000Z",
  },
  {
    id: "VOC-CHM-017",
    contributor_id: "usr_contrib_15",
    contributor_name: "Tsering Verma",
    dialect: "Chameali",
    word_devanagari: "घुरई",
    meaning: "जंगलों में पाई जाने वाली जंगली तीतर या पक्षी विशेष।",
    example_sentence: "जंगला च घुरई सुणी दी थी।",
    region: "Pangi",
    category: "Animals & Wildlife",
    word_latin: "ghurai",
    ipa: "ɡʱuɾəiː",
    meaning_hindi: "जंगली तीतर",
    meaning_english: "Himalayan monal pheasant variant or hill partridge",
    example_sentence_english:
      "The hill pheasant was heard singing in the woods.",
    example_sentence_hindi: "जंगल में जंगली तीतर की आवाज सुनाई दी थी।",
    status: "approved",
    review_comments: [],
    history: [
      {
        id: "HE-CHM-017A",
        type: "submitted",
        actor_id: "usr_contrib_15",
        actor_name: "Tsering Verma",
        message: "Fauna observation logs.",
        created_at: "2026-07-04T12:00:00.000Z",
      },
      {
        id: "HE-CHM-017B",
        type: "approved",
        actor_id: "usr_admin_01", // SuperAdmin approval log directly
        actor_name: "System Root Executive",
        message: "Automated standard batch approval.",
        created_at: "2026-07-04T15:00:00.000Z",
      },
    ],
    flag_reason: null,
    flagged_by: null,
    rejected_reason: null,
    rejected_by: null,
    approved_by: "System Root Executive",
    approved_at: "2026-07-04T15:00:00.000Z",
    created_at: "2026-07-04T11:40:00.000Z",
    updated_at: "2026-07-04T15:00:00.000Z",
  },
  {
    id: "VOC-SIR-018",
    contributor_id: "usr_contrib_18",
    contributor_name: "Kabir Chauhan",
    dialect: "Sirmauri",
    word_devanagari: "डगरा",
    meaning:
      "पहाड़ी पत्थरों और पगडंडियों को काटकर बनाया गया संकरा चौड़ा रास्ता।",
    example_sentence: "ऐस डगरा च संभली करी चला।",
    region: "Shillai",
    category: "Nature & Geography",
    word_latin: "dagra",
    ipa: "ɖəɡɾaː",
    meaning_hindi: "रास्ता या पगडंडी",
    meaning_english: "Rocky mountain pathway",
    example_sentence_english: "Walk carefully on this steep mountain pathway.",
    example_sentence_hindi: "इस पगडंडी पर संभलकर चलो।",
    status: "flagged",
    review_comments: [
      {
        id: "RC-SIR-018A",
        author_id: "usr_head_11",
        author_name: "Meera Thakur",
        field_name: "IPA",
        message: "The flap r sound is highly prominent here, fix notation.",
        status: "open", // open comment inside a flagged state -> test if Language Head can clear it.
        created_at: "2026-07-06T11:22:00.000Z",
        resolved_at: null,
        resolved_by: null,
      },
    ],
    history: [
      {
        id: "HE-SIR-018A",
        type: "submitted",
        actor_id: "usr_contrib_18",
        actor_name: "Kabir Chauhan",
        message: "Submitted transport pathway logs.",
        created_at: "2026-07-06T10:10:00.000Z",
      },
      {
        id: "HE-SIR-018B",
        type: "flagged",
        actor_id: "usr_head_11",
        actor_name: "Meera Thakur",
        message: "Flagged because IPA requires acoustic check.",
        created_at: "2026-07-06T11:25:00.000Z",
      },
    ],
    flag_reason: "Phonological dispute on retroflexion intensity.",
    flagged_by: "Meera Thakur",
    rejected_reason: null,
    rejected_by: null,
    approved_by: null,
    approved_at: null,
    created_at: "2026-07-06T09:50:00.000Z",
    updated_at: "2026-07-06T11:25:00.000Z",
  },
  {
    id: "VOC-KNG-019",
    contributor_id: "usr_contrib_22",
    contributor_name: "Priya Katoch",
    dialect: "Kangri",
    word_devanagari: "चिल्डू",
    meaning:
      "स्थानीय स्तर पर गेहूं के पतले घोल से बनाया जाने वाला स्वादिष्ट नमकीन चीला।",
    example_sentence: "अज्ज अहां चिल्डू बणाणे न।",
    region: "Dehra",
    category: "Food & Culinary",
    word_latin: "childu",
    ipa: "t͡ʃɪlɖuː",
    meaning_hindi: "चीला",
    meaning_english: "Savory thin wheat pancake pancake",
    example_sentence_english:
      "Today we are going to make thin savory wheat pancakes.",
    example_sentence_hindi: "आज हम चीला बनाने वाले हैं।",
    status: "under_review",
    review_comments: [
      {
        id: "RC-KNG-019A",
        author_id: "usr_expert_77",
        author_name: "Jasper Dahl",
        field_name: "Meaning English",
        message: "Duplicate word 'pancake pancake' needs cleanup.",
        status: "open",
        created_at: "2026-07-07T17:00:00.000Z",
        resolved_at: null,
        resolved_by: null,
      },
    ],
    history: [
      {
        id: "HE-KNG-019A",
        type: "submitted",
        actor_id: "usr_contrib_22",
        actor_name: "Priya Katoch",
        message: "Uploaded culinary metadata.",
        created_at: "2026-07-07T16:15:00.000Z",
      },
      {
        id: "HE-KNG-019B",
        type: "comment_added",
        actor_id: "usr_expert_77",
        actor_name: "Jasper Dahl",
        message: "Pointed out a typo error.",
        created_at: "2026-07-07T17:00:00.000Z",
      },
    ],
    flag_reason: null,
    flagged_by: null,
    rejected_reason: null,
    rejected_by: null,
    approved_by: null,
    approved_at: null,
    created_at: "2026-07-07T16:00:00.000Z",
    updated_at: "2026-07-07T17:00:00.000Z",
  },
  {
    id: "VOC-MND-020",
    contributor_id: "usr_expert_77", // Expert submitting their own data
    contributor_name: "Jasper Dahl",
    dialect: "Mandyali",
    word_devanagari: "टटयार",
    meaning:
      "बरसात के मौसम में तेज तीखी आवाज निकालने वाला कीड़ा या टिड्डा विशेष।",
    example_sentence: "रात जो टटयार मते बोलदे न।",
    region: "Chachiot",
    category: "Animals & Wildlife",
    word_latin: "tatyar",
    ipa: "ʈəʈjaːɾ",
    meaning_hindi: "टिड्डा या झींगुर",
    meaning_english: "Monsoon cicada or loud field cricket",
    example_sentence_english: "The cicadas chirp loudly during the night.",
    example_sentence_hindi: "रात को झींगुर बहुत बोलते हैं।",
    status: "under_review",
    review_comments: [
      {
        id: "RC-MND-020A",
        author_id: "usr_expert_21",
        author_name: "Dev Sharma",
        field_name: "Meaning English",
        message:
          "Is it a cicada or a cricket family insect? Clarify taxo entry.",
        status: "open", // Another expert opens an objection. Jasper cannot approve this himself because of rule engine checks.
        created_at: "2026-07-07T19:00:00.000Z",
        resolved_at: null,
        resolved_by: null,
      },
    ],
    history: [
      {
        id: "HE-MND-020A",
        type: "submitted",
        actor_id: "usr_expert_77",
        actor_name: "Jasper Dahl",
        message: "Insect fauna database item saved.",
        created_at: "2026-07-07T18:22:00.000Z",
      },
      {
        id: "HE-MND-020B",
        type: "comment_added",
        actor_id: "usr_expert_21",
        actor_name: "Dev Sharma",
        message: "Requested specialized insect clarification.",
        created_at: "2026-07-07T19:00:00.000Z",
      },
    ],
    flag_reason: null,
    flagged_by: null,
    rejected_reason: null,
    rejected_by: null,
    approved_by: null,
    approved_at: null,
    created_at: "2026-07-07T18:00:00.000Z",
    updated_at: "2026-07-07T19:00:00.000Z",
  },
  {
    id: "VOC-KUL-021",
    contributor_id: "usr_contrib_14",
    contributor_name: "Rohit Negi",
    dialect: "Kulluvi",
    word_devanagari: "पलीछणा",
    meaning:
      "उबलते हुए चावलों से अतिरिक्त पानी (मांड) को बाहर निथारना या अलग करना।",
    example_sentence: "भात पलीछी करी खाणा चाहिंदा।",
    region: "Banjar",
    category: "Household Objects",
    word_latin: "palichana",
    ipa: "pəliːt͡ʃʰəɳaː",
    meaning_hindi: "मांड निकालना",
    meaning_english: "To drain excess starchy water from boiled rice",
    example_sentence_english:
      "Rice should be eaten after draining the starchy water.",
    example_sentence_hindi: "चावल मांड निकालकर खाना चाहिए।",
    status: "approved",
    review_comments: [],
    history: [
      {
        id: "HE-KUL-021A",
        type: "submitted",
        actor_id: "usr_contrib_14",
        actor_name: "Rohit Negi",
        message: "Submitted local action verb entry.",
        created_at: "2026-07-03T14:00:00.000Z",
      },
      {
        id: "HE-KUL-021B",
        type: "approved",
        actor_id: "usr_head_11",
        actor_name: "Meera Thakur",
        message: "Directly approved high quality systemic verb representation.",
        created_at: "2026-07-03T16:00:00.000Z",
      },
    ],
    flag_reason: null,
    flagged_by: null,
    rejected_reason: null,
    rejected_by: null,
    approved_by: "Meera Thakur",
    approved_at: "2026-07-03T16:00:00.000Z",
    created_at: "2026-07-03T13:45:00.000Z",
    updated_at: "2026-07-03T16:00:00.000Z",
  },
  {
    id: "VOC-SIR-022",
    contributor_id: "usr_contrib_18",
    contributor_name: "Kabir Chauhan",
    dialect: "Sirmauri",
    word_devanagari: "बथांण",
    meaning:
      "पालतू मवेशियों को बांधने और उनके विश्राम के लिए बनाया गया बाड़ा या गौशाला।",
    example_sentence: "गोरूआं जो बथांणा दी हंकी दे।",
    region: "Sangrah",
    category: "Agriculture & Land",
    word_latin: "bathan",
    ipa: "bət̪ʰaːɳ",
    meaning_hindi: "गौशाला या पशुशाला",
    meaning_english: "Cattle shed or open corral setup",
    example_sentence_english:
      "Herd the domestic cattle inside the shed shelter.",
    example_sentence_hindi: "पशुओं को गौशाला में हांक दो।",
    status: "under_review",
    review_comments: [
      {
        id: "RC-SIR-022A",
        author_id: "usr_expert_21",
        author_name: "Dev Sharma",
        field_name: "Category",
        message: "Should this be under Household Objects or Agriculture?",
        status: "rejected", // Test case for comment rejection workflow status
        created_at: "2026-07-05T12:00:00.000Z",
        resolved_at: "2026-07-05T13:40:00.000Z",
        resolved_by: "usr_head_11",
      },
    ],
    history: [
      {
        id: "HE-SIR-022A",
        type: "submitted",
        actor_id: "usr_contrib_18",
        actor_name: "Kabir Chauhan",
        message: "Submitted ranch structures data.",
        created_at: "2026-07-05T11:00:00.000Z",
      },
      {
        id: "HE-SIR-022B",
        type: "comment_rejected",
        actor_id: "usr_head_11",
        actor_name: "Meera Thakur",
        message: "Overruled categorization objection; agriculture fits best.",
        created_at: "2026-07-05T13:40:00.000Z",
      },
    ],
    flag_reason: null,
    flagged_by: null,
    rejected_reason: null,
    rejected_by: null,
    approved_by: null,
    approved_at: null,
    created_at: "2026-07-05T10:30:00.000Z",
    updated_at: "2026-07-05T13:40:00.000Z",
  },
  {
    id: "VOC-CHM-023",
    contributor_id: "usr_contrib_15",
    contributor_name: "Tsering Verma",
    dialect: "Chameali",
    word_devanagari: "न्ह्यार",
    meaning: "खेत जोतने वाले बैलों के गले में डाली जाने वाली भारी लकड़ी (जुआ)।",
    example_sentence: "बळदां दे गळ च न्ह्यार रखी दे।",
    region: "Chamba",
    category: "Agriculture & Land",
    word_latin: "nhyar",
    ipa: "nçjaːɾ",
    meaning_hindi: "जुआ (बैलों का)",
    meaning_english: "Wooden yoke used for plowing animals",
    example_sentence_english:
      "Place the heavy wooden yoke upon the oxen's necks.",
    example_sentence_hindi: "बैलों के गले में जुआ रख दो।",
    status: "flagged",
    review_comments: [], // Edge case: Flagged entry with NO comments. Contributor can still edit it, but standard experts cannot touch it.
    history: [
      {
        id: "HE-CHM-023A",
        type: "submitted",
        actor_id: "usr_contrib_15",
        actor_name: "Tsering Verma",
        message: "Submitted structural farm implement entry.",
        created_at: "2026-07-04T09:00:00.000Z",
      },
      {
        id: "HE-CHM-023B",
        type: "flagged",
        actor_id: "usr_admin_01",
        actor_name: "System Root Executive",
        message: "Flagged processing block until character parsing validated.",
        created_at: "2026-07-04T10:15:00.000Z",
      },
    ],
    flag_reason: "Unicode clusters in Devanagari onset require verification.",
    flagged_by: "System Root Executive",
    rejected_reason: null,
    rejected_by: null,
    approved_by: null,
    approved_at: null,
    created_at: "2026-07-04T08:30:00.000Z",
    updated_at: "2026-07-04T10:15:00.000Z",
  },
  {
    id: "VOC-KNG-024",
    contributor_id: "usr_contrib_22",
    contributor_name: "Priya Katoch",
    dialect: "Kangri",
    word_devanagari: "झुळमुळ",
    meaning:
      "शाम का वह समय जब दिन ढल चुका हो पर पूरी तरह अंधेरा न हुआ हो (गोधूलि बेला)।",
    example_sentence: "झुळमुळा रे बकत कतै मत जाणा।",
    region: "Hamirpur",
    category: "Time & Seasons",
    word_latin: "jhulmul",
    ipa: "ɟʱʊڵmʊڵ",
    meaning_hindi: "गोधूलि बेला",
    meaning_english: "Dusk or twilight time frame",
    example_sentence_english:
      "Do not travel anywhere out during twilight hours.",
    example_sentence_hindi: "गोधूलि बेला के समय कहीं मत जाना।",
    status: "under_review",
    review_comments: [
      {
        id: "RC-KNG-024A",
        author_id: "usr_expert_77",
        author_name: "Jasper Dahl",
        field_name: "IPA",
        message: "Confirm lateral sound variant usages.",
        status: "open",
        created_at: "2026-07-07T21:00:00.000Z",
        resolved_at: null,
        resolved_by: null,
      },
    ],
    history: [
      {
        id: "HE-KNG-024A",
        type: "submitted",
        actor_id: "usr_contrib_22",
        actor_name: "Priya Katoch",
        message: "Submitted twilight metadata.",
        created_at: "2026-07-07T20:00:00.000Z",
      },
      {
        id: "HE-KNG-024B",
        type: "comment_added",
        actor_id: "usr_expert_77",
        actor_name: "Jasper Dahl",
        message:
          "Question raised regarding subdialect lateral representations.",
        created_at: "2026-07-07T21:00:00.000Z",
      },
    ],
    flag_reason: null,
    flagged_by: null,
    rejected_reason: null,
    rejected_by: null,
    approved_by: null,
    approved_at: null,
    created_at: "2026-07-07T19:30:00.000Z",
    updated_at: "2026-07-07T21:00:00.000Z",
  },
];
